<?php 
session_start();
require_once("appointLib.php");

if (!isset($_SESSION['user_id'])) {
    header("Location: auth.php");
    exit();
}

if (isset($_GET['id']) && !empty($_GET['id'])) {
    $appointment = new Appointment();
    $appointment->setId($_GET['id']);
    
    // Check ownership before processing the deletion
    $currentRecord = $appointment->getAppointment();
    
    if (!$currentRecord) {
        header("Location: users.php");
        exit();
    }

    // Patients can only alter row data explicitly generated by their own accounts
    if ($_SESSION['user_role'] === 'patient' && $currentRecord->user_id != $_SESSION['user_id']) {
        header("Location: users.php?error=unauthorized");
        exit();
    }

    if ($appointment->deleteAppointment()) {
        // Route path checks depending on who triggered the deletion
        if ($_SESSION['user_role'] === 'doctor') {
            header("Location: doctor.php?deleted=1");
        } else {
            header("Location: users.php?deleted=1");
        }
        exit();
    } else {
        echo "Error: High level structural update rejection.";
    }
} else {
    header("Location: auth.php");
    exit();
}
?>